blog/urls.py
from django.urls import include, path
from blog import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.render_articles, name='index'),
    path('menus', views.menus, name = 'menus'),
    path('registro', views.registro , name = 'registro'),
    path('nosotros', views.nosotros, name = 'nosotros'),
    path('contacto', views.contacto, name = 'contacto'),
    path('login', views.login, name = 'login'),
    path('registro', views.registro, name = 'registro'),
    path('crud', views.crud, name = 'crud'),
    path('pago', views.pago, name = 'pago'),   
    path('agregar/<int:menu_id>/', views.agregar_menu, name='Add'),
    path('eliminar/<int:menu_id>/', views.eliminar_menu, name='Del'),
    path('restar/<int:menu_id>/', views.restar_menu, name='Sub'),
    path('limpiar/', views.limpiar_carrito, name='CLS'),
    path('agregar-producto/', views.agregar_producto, name='agregar_producto'),
    path('perfil/', views.perfil, name='perfil'),
    path('modificar-producto/<id>/', views.modificar_producto, name='modificar_producto'),
    path('editar_contacto/<int:id>/', views.editar_contacto, name='editar_contacto'),
    path('guardar_pedido/', views.guardar_pedido, name='guardar_pedido'),
    path('revisar_pedidos/', views.revisar_pedidos, name='revisar_pedidos'),
    path('menu/<int:menu_id>/', views.detalle_menu, name='detalle_menu'),
    path('agregar-proteina/', views.agregar_proteina, name='agregar_proteina'),
    path('agregar-salsa/', views.agregar_salsa, name='agregar_salsa'),
    path('agregar-vegetal/', views.agregar_vegetal, name='agregar_vegetal'),
    path('ingredientes/', views.lista_ingredientes, name='lista_ingredientes'),
    path('proteina/editar/<int:id>/', views.editar_proteina, name='editar_proteina'),
    path('proteina/eliminar/<int:id>/', views.eliminar_proteina, name='eliminar_proteina'),
    path('vegetal/editar/<int:id>/', views.editar_vegetal, name='editar_vegetal'),
    path('vegetal/eliminar/<int:id>/', views.eliminar_vegetal, name='eliminar_vegetal'),
    path('salsa/editar/<int:id>/', views.editar_salsa, name='editar_salsa'),
    path('salsa/eliminar/<int:id>/', views.eliminar_salsa, name='eliminar_salsa'),
    path('editar-usuario/', views.editar_usuario, name='editar_usuario'),
  
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    

]

    

menus/urls.py
from rest_framework import routers
from .views import MenuViewSet

router = routers.DefaultRouter()
router.register(r'menu', MenuViewSet, basename='menu')

urlpatterns = router.urls

pedidos/urls.py
from rest_framework import routers
from .views import PedidoViewSet

router = routers.DefaultRouter()
router.register(r'pedido', PedidoViewSet, basename='pedido')

urlpatterns = router.urls

santfood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('api/contactos/', include('contactos.urls')),
    path('api/menus/', include('menus.urls')),
    path('api/pedidos/', include('pedidos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

contactos/models.py
from django.db import models
from django.core.validators import MinValueValidator, RegexValidator, MinLengthValidator, EmailValidator
from django.db import models
from django.core.validators import (
    MinLengthValidator,
    RegexValidator,
    EmailValidator,
    ValidationError,
)
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError as DjangoValidationError

# Create your models here.


class Tipo_contacto(models.Model):
    tipo_contacto = models.CharField(
        max_length=20,
        validators=[
            MinLengthValidator(3),
            RegexValidator(
                regex='^[a-zA-ZñÑ]+$',
                message='El tipo de contacto solo puede contener letras y debe ser mayor a 3 letras'
            ),
        ]
    )

    def __str__(self):
        return self.tipo_contacto
    
class Estado_contacto(models.Model):
    estado_contacto = models.CharField(max_length=50)

    def __str__(self):
        return self.estado_contacto



def validate_unique_chars(value):
    previous_char = ''
    for char in value:
        if char == previous_char:
            raise ValidationError(
                _('El campo no puede contener caracteres repetidos consecutivos.'),
                code='invalid'
            )
        previous_char = char
        
def validate_message_sense(value):
    if len(set(value.lower())) < 10:
        raise ValidationError(
            _('El mensaje debe contener al menos 10 caracteres diferentes.'),
            code='invalid'
        )

class Contacto(models.Model):
    nombre = models.CharField(
        max_length=100,
        validators=[
            MinLengthValidator(3, message='El nombre debe tener al menos 3 caracteres'),
            RegexValidator(
                regex=r'^[a-zA-ZñÑ]+$',
                message='El nombre solo puede contener letras',
                code='invalid_nombre'
            ),
            validate_unique_chars
        ]
    )
    correo = models.EmailField(
    validators=[
        EmailValidator(message='Introduzca una dirección de correo electrónico válida'),
        RegexValidator(
            regex=r'^[^@]+@[a-zA-Z0-9.]{5,}\.[a-zA-Z]{2,4}$',
            message='El correo debe tener al menos 5 caracteres después del "@" y terminar en ".cl" o ".com"',
            code='invalid_correo'
            )
        ]
    )
    tipo_contacto = models.ForeignKey(Tipo_contacto, on_delete=models.PROTECT)
    mensaje_contacto = models.CharField(
        max_length=300,
        validators=[
            MinLengthValidator(10, message='El mensaje debe tener al menos 10 caracteres'),
            RegexValidator(
                regex=r'^(?!.*([^a-zA-Z. ñÑáéíóúÁÉÍÓÚ])).*$',
                message='El mensaje solo puede contener letras y puntos. Además, no pueden ser solo puntos.',
                code='invalid_mensaje_contacto'
            ),
            validate_unique_chars,
            validate_message_sense
        ]
    )
    estado_contacto = models.ForeignKey(Estado_contacto, on_delete=models.SET_DEFAULT, default=1, blank=True, null=True)
    respuesta = models.TextField(blank=True, null=True)
    
    def save(self, *args, **kwargs):
        if not self.nombre.strip():
            raise DjangoValidationError(_('El nombre no puede estar vacío o contener solo espacios en blanco.'))
        if not self.correo.strip():
            raise DjangoValidationError(_('El correo no puede estar vacío o contener solo espacios en blanco.'))
        if not self.mensaje_contacto.strip():
            raise DjangoValidationError(_('El mensaje no puede estar vacío o contener solo espacios en blanco.'))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nombre

menus/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, RegexValidator, MinLengthValidator


# Create your models here.

def no_tres_caracteres_repetidos(value):
    if len(value) >= 3:
        if value[0] == value[1] == value[2]:
            raise ValidationError(
                'El nombre no puede consistir en tres caracteres repetidos.',
                code='invalid'
            )

class Categoria(models.Model):
    nombre = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(3),
            no_tres_caracteres_repetidos,
            RegexValidator(
                regex='^[a-zA-ZñÑ ]+$',
                message='El nombre de la categoria solo puede contener letras y debe ser mayor a 3 letras'
            ),
        ],
        unique=True,
    )

    def __str__(self):
        return self.nombre

class Proteina(models.Model):
    nombre = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(3),
            no_tres_caracteres_repetidos,
            RegexValidator(
                regex='^[a-zA-ZñÑ ]+$',
                message='El nombre de la proteina solo puede contener letras y debe ser mayor a 3 letras'
            ),
        ],
        unique= True,
    )

    def __str__(self):
        return self.nombre
    
class Vegetal(models.Model):
    nombre = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(3),
            no_tres_caracteres_repetidos,
            RegexValidator(
                regex='^[a-zA-ZñÑ ]+$',
                message='El nombre del vegetal solo puede contener letras y debe ser mayor a 3 letras'
            ),
        ],
        unique=True,
    )

    def __str__(self):
        return self.nombre
    
class Salsa(models.Model):
    nombre = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(3),
            no_tres_caracteres_repetidos,
            RegexValidator(
                regex='^[a-zA-ZñÑ ]+$',
                message='El nombre de la salsa solo puede contener letras y debe ser mayor a 3 letras'
            ),
        ],
        unique=True,
    )

    def __str__(self):
        return self.nombre


class Menu(models.Model):
    nombre_menu = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(8),
            no_tres_caracteres_repetidos,
            RegexValidator(
                regex='^[A-ZÑ][a-zA-ZñÑ ]+$',
                message='El nombre del menú debe comenzar con una letra mayúscula y solo puede contener letras y espacios.',
                code='invalid_nombre_menu'
            )
        ]
    )
    precio = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    ganancia = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    estado_menu = models.BooleanField()
    descripcion_menu = models.CharField(
        max_length=300,
        validators=[
            MinLengthValidator(10),
            RegexValidator(
                regex=r'^(?!^[.\s]*$)[a-zA-Z0-9áéíóúñÑÁÉÍÓÚ.,\s]+$',
                message='La descripción solo puede contener letras, números, puntos y espacios. No puede estar compuesta solo por puntos o espacios.',
                code='invalid_descripcion_menu'
            )
        ]
    )
    imagen = models.ImageField(upload_to='images/')
    proteina = models.ManyToManyField(Proteina)
    vegetal = models.ManyToManyField(Vegetal)
    salsa = models.ManyToManyField(Salsa)
    categoria = models.ManyToManyField(Categoria)
    stock = models.PositiveIntegerField()

    def __str__(self):
        return self.nombre_menu

    def clean(self):
        super().clean()

        if not self.descripcion_menu or len(self.descripcion_menu) < 10:
            raise ValidationError({
                'descripcion_menu': 'La descripción debe tener al menos 10 caracteres.'
            })


    

    

blog/forms.py
import re
from django import forms
from django.contrib.auth.forms import UserCreationForm
from menus.models import Menu, Proteina, Salsa, Vegetal
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user_id = self.instance.id if self.instance else None 
        
        if User.objects.exclude(id=user_id).filter(email=email).exists():
            raise forms.ValidationError('Este email ya está en uso. Por favor, elige otro.')
        
        return email
    
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if not re.match(r'^[A-Za-zñÑ]{1,15}$', first_name):
            raise forms.ValidationError('El nombre debe contener solo letras, máximo 15 caracteres y sin espacios.')

        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')

        if not re.match(r'^[A-Za-zñÑ ]{1,30}$', last_name):
            raise forms.ValidationError('Los apellidos debe contener solo letras y espacios, máximo 30 caracteres.')

        return last_name
    
    def clean_username(self):
        username = self.cleaned_data.get('username')

        if not re.match(r'^[A-Za-zñÑ]{1,15}$', username):
            raise forms.ValidationError('El username debe contener solo letras, máximo 15 caracteres y sin espacios.')

        return username


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='Email', max_length=254,
        validators=[
            RegexValidator(
                regex=r'^[^@]+@[a-zA-Z0-9.]{5,}\.[a-zA-Z]{2,4}$',
                message='El correo debe tener al menos 5 caracteres después del "@" y terminar en ".cl" o ".com"',
                code='invalid_email'
            )
        ]
    )

    username = forms.CharField(label='Username',
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z0-9]+$',
                message='El nombre de usuario solo puede contener letras y números',
                code='invalid_username'
            )
        ]
    )

    def clean_username(self):
        username = self.cleaned_data['username']
        
        # Validar caracteres repetidos consecutivos
        previous_char = ''
        for char in username:
            if char == previous_char:
                raise ValidationError('El nombre de usuario no puede contener caracteres repetidos consecutivos.')
            previous_char = char
        
        return username

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')




class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'
        widgets = {
            'proteina': forms.CheckboxSelectMultiple,
            'vegetal': forms.CheckboxSelectMultiple,
            'salsa': forms.CheckboxSelectMultiple,
            'categoria': forms.CheckboxSelectMultiple,
        }

class ProteinaForm(forms.ModelForm):
    class Meta:
        model = Proteina
        fields = ['nombre']

class SalsaForm(forms.ModelForm):
    class Meta:
        model = Salsa
        fields = ['nombre']

class VegetalForm(forms.ModelForm):
    class Meta:
        model = Vegetal
        fields = ['nombre']
        

contactos/forms.py
from django import forms
from .models import Contacto


class ContactoForm(forms.ModelForm):
    
    class Meta:
        model = Contacto
        fields = ["nombre", "correo", "tipo_contacto", "mensaje_contacto"]
        
        


class ContactoAdminForm(forms.ModelForm):
    respuesta = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Contacto
        fields = ["estado_contacto", "respuesta"]

    def __init__(self, *args, **kwargs):
        super(ContactoAdminForm, self).__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            if field_name not in ["estado_contacto", "respuesta"]:
                field.widget.attrs['readonly'] = True

contactos/views.py
from django.shortcuts import render
from rest_framework import viewsets
from .models import Contacto, Estado_contacto, Tipo_contacto
from .serializer import ContactoSerializer, Estado_contactoSerializer, Tipo_contactoSerializer

# Create your views here.
class ContactoViewSet(viewsets.ModelViewSet):
    queryset = Contacto.objects.all()
    serializer_class = ContactoSerializer

class Tipo_contactoViewSet(viewsets.ModelViewSet):
    queryset = Tipo_contacto.objects.all()
    serializer_class = Tipo_contactoSerializer

class Estado_contactoViewSet(viewsets.ModelViewSet):
    queryset = Estado_contacto.objects.all()
    serializer_class = Estado_contactoSerializer

menus/views.py
from django.shortcuts import render
from rest_framework import viewsets
from .models import Menu
from .serializer import MenuSerializer

# Create your views here.

class MenuViewSet(viewsets.ModelViewSet):
    queryset = Menu.objects.all()
    serializer_class = MenuSerializer


    

pedidos/views.py
from django.shortcuts import render
from rest_framework import viewsets
from .models import Pedido
from .serializer import PedidoSerializer  

# Create your views here.
class PedidoViewSet(viewsets.ModelViewSet):
    queryset = Pedido.objects.all()
    serializer_class = PedidoSerializer

blog/templates/contacto.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block contenido %}

<br><br>
<div class="container-form-contacto">
    <div class="information-contacto">
        <div class="info-childs-contacto">
            <h2>Dejanos Tu Comentario</h2>
            <p>Puedes realizar una sugerencia, reclamo o felicitaciones hacia nuestros colaboradores.</p>
            <br>
        </div>
    </div>
    <div class="form-information-contacto">
        <div class="form-information-childs-contacto">
            <h2>CONTACTANOS</h2>

            {% if messages %}
                <div class="alert-container">
                    {% for message in messages %}
                        <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <form action="" method="post" class="formulario_contacto">
                {% csrf_token %}
                {{ form|crispy }}

                <input type="submit" value="Enviar" class="btn btn-primary">
                <input type="reset" value="Limpiar" class="btn btn-secondary">
            </form>
        </div>
    </div>
</div>
<br><br>

{% endblock %}

{% comment %} {% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}


{% block contenido %}

<br><br>
<div class="container-form-contacto">
    <div class="information-contacto">
        <div class="info-childs-contacto">
            <h2>Dejanos Tu Comentario</h2>
            <p>Puedes realizar una sugerencia, reclamo o felicitaciones hacia nuestros <colaboradores></colaboradores></p>
            <br>
        </div>
    </div>
    <div class="form-information-contacto">
        <div class="form-information-childs-contacto">
            <h2>CONTACTANOS</h2>

            {% if messages %}
                <div class="alert-container">
                    {% for message in messages %}
                        <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}

            <form action="" method="post" class="formulario_contacto">
                <div class="contacto">
                    {% csrf_token %}
                    {{ form|crispy }}
                </div>
                <br>
                <input type="submit" value="Enviar" class="btn btn-primary">
                <input type="reset" value="Limpiar" class="btn btn-secondary">
            </form>
        </div>
    </div>
</div>
<br><br>

{% endblock %} {% endcomment %}

blog/templates/crud.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
{% if user.username == 'admin' %}


<div class="container-fluid">
    <form class="crud" method="get" action="">
        <label for="id_estado_contacto">Filtrar por estado de contacto:</label>
        <select name="estado_contacto" id="id_estado_contacto">
            <option value="">Todos</option>
            {% for estado in estados_contacto %}
                <option value="{{ estado.id }}">{{ estado.estado_contacto }}</option>
            {% endfor %}
        </select>
    
        <label for="id_tipo_contacto">Filtrar por tipo de contacto:</label>
        <select name="tipo_contacto" id="id_tipo_contacto">
            <option value="">Todos</option>
            {% for tipo in tipos_contacto %}
                <option value="{{ tipo.id }}">{{ tipo.tipo_contacto }}</option>
            {% endfor %}
        </select>
        <div class="d-flex justify-content-between"> <!-- Utilizamos flexbox para alinear los botones -->
            <button type="submit" class="btn btn-primary flex-fill me-2">Filtrar</button> <!-- btn-primary para color azul -->
            <a href="{% url 'lista_ingredientes' %}" class="btn btn-secondary flex-fill">Quitar Filtro</a> <!-- btn-secondary para color gris -->
        </div>
    </form>
    
    


  <div class="card-container">
    {% for contacto in contactos %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ contacto.nombre }}</h5>
            <p class="card-text">Tipo de contacto: {{ contacto.tipo_contacto }}</p>
            <p class="card-text">Estado: {{ contacto.estado_contacto.estado_contacto }}</p>
            <p class="card-text">{{ contacto.mensaje_contacto }}</p>
        </div>
        <div class="card-footer">
            <a href="{% url 'editar_contacto' contacto.id %}" class="btn-3">Editar</a>
        </div>
    </div>
    {% endfor %}
  </div>

</div>

<br>

{% else %}
<div class="card">
    <h1>No tienes los permisos para ingresar a esta página</h1>
    <a href="{% url 'index' %}">Volver al inicio</a>
</div>
{% endif %}
{% endblock %}

blog/templates/editar_usuario.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
    {% load crispy_forms_tags %}
    {% if user.is_authenticated %}
    
        <br><br>
        <div class="container-agregar">
            {% if messages %}
                <div class="alert-container">
                    {% for message in messages %}
                        <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            
            <form method="post">
                <div>
                    {% csrf_token %}
                    {{ form|crispy }}
                </div>
                <div class = "text-center">
                <button type="submit" class="btn btn-primary">Guardar cambios</button>
                </div>
            </form>
        </div>
    
    {% else %}
    
        <div class="card">
            <h1>No tienes los permisos para ingresar a esta página</h1>
            <a href="{% url 'index' %}">Volver al inicio</a>
        </div>
    
    {% endif %}
    <br><br>
{% endblock %}

blog/templates/lista_ingredientes.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
{% if user.username == 'admin' %}

<div class="container-fluid">
  <form class="crud" method="get" action="">
    <div class="form-group">
        <label for="id_proteina">Filtrar por proteína:</label>
        <input type="text" name="proteina" id="id_proteina" class="form-control" placeholder="Nombre de la proteína">
    </div>
    <div class="form-group">
        <label for="id_vegetal">Filtrar por vegetal:</label>
        <input type="text" name="vegetal" id="id_vegetal" class="form-control" placeholder="Nombre del vegetal">
    </div>
    <div class="form-group">
        <label for="id_salsa">Filtrar por salsa:</label>
        <input type="text" name="salsa" id="id_salsa" class="form-control" placeholder="Nombre de la salsa">
    </div>
    <div class="d-flex justify-content-between"> <!-- Utilizamos flexbox para alinear los botones -->
        <button type="submit" class="btn btn-primary flex-fill me-2">Filtrar</button> <!-- btn-primary para color azul -->
        <a href="{% url 'lista_ingredientes' %}" class="btn btn-secondary flex-fill">Quitar Filtro</a> <!-- btn-secondary para color gris -->
    </div>
  </form>
  <br><br>

  {% if messages %}
  <div class="alert-container">
    {% for message in messages %}
        <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
  </div>
  {% endif %}
            <div class="container">
                <div class="card mb-4">
                  <div class="card-header">
                    <h3>Proteínas</h3><a href="{% url 'agregar_proteina' %}" class="btn btn-success">+</a>
                  </div>
                  <div class="card-body">
                    <div class="row">
                      {% for proteina in proteinas %}
                      <div class="col-md-4">
                        <div class="card mb-4">
                          <div class="card-body">
                            <h5 class="card-title">{{ proteina.nombre }}</h5>
                          </div>
                          <div class="card-footer">
                            <a href="{% url 'editar_proteina' proteina.id %}" class="btn btn-secondary">Editar</a>
                            <form action="{% url 'eliminar_proteina' proteina.id %}" method="post" style="display:inline;">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-danger">Eliminar</button>
                            </form>
                          </div>
                        </div>
                      </div>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              
                <div class="card mb-4">
                  <div class="card-header">
                    <h3>Vegetales</h3><a href="{% url 'agregar_vegetal' %}" class="btn btn-success">+</a>
                  </div>
                  <div class="card-body">
                    <div class="row">
                      {% for vegetal in vegetales %}
                      <div class="col-md-4">
                        <div class="card mb-4">
                          <div class="card-body">
                            <h5 class="card-title">{{ vegetal.nombre }}</h5>
                          </div>
                          <div class="card-footer">
                            <a href="{% url 'editar_vegetal' vegetal.id %}" class="btn btn-secondary">Editar</a>
                            <form action="{% url 'eliminar_vegetal' vegetal.id %}" method="post" style="display:inline;">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-danger">Eliminar</button>
                            </form>
                          </div>
                        </div>
                      </div>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                <div class="card mb-4">
                  <div class="card-header">
                    <h3>Salsas</h3><a href="{% url 'agregar_salsa' %}" class="btn btn-success">+</a>
                  </div>
                  <div class="card-body">
                    <div class="row">
                      {% for salsa in salsas %}
                      <div class="col-md-4">
                        <div class="card mb-4">
                          <div class="card-body">
                            <h5 class="card-title">{{ salsa.nombre }}</h5>
                          </div>
                          <div class="card-footer">
                            <a href="{% url 'editar_salsa' salsa.id %}" class="btn btn-secondary">Editar</a>
                            <form action="{% url 'eliminar_salsa' salsa.id %}" method="post" style="display:inline;">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-danger">Eliminar</button>
                            </form>
                          </div>
                        </div>
                      </div>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              
              </div>

                
            
{% else %}
<div class="card">
    <h1>No tienes los permisos para ingresar a esta página</h1>
    <a href="{% url 'index' %}">Volver al inicio</a>
</div>
{% endif %}
{% endblock %}

blog/templates/menus.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}  <!-- Asegúrate de cargar el filtro intcomma -->

{% block contenido %}
{% if messages %}
    <div class="alert-container">
        {% for message in messages %}
            <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}
<div class="menu-compras">
    {% for menu in menus %}
        {% if user.username == 'admin' or menu.stock > 0 %}
            <div class="food-items" id="lista">
                <img src="{{ menu.imagen.url }}"/>
                <div class="contenido-principal">
                    <div class="detalles">
                        <div class="detalles-categoria">
                            <h5>{{ menu.nombre_menu }}</h5>
                            <br>
                            <p>{{ menu.descripcion_menu }}</p>
                            <br>
                            {% with precio_entero=menu.precio|intcomma %}
                                <p class="precio">Precio: ${{ precio_entero }}</p>
                            {% endwith %}
                            {% if user.username == 'admin' %}
                                <p>Estado: {{ menu.estado_menu|yesno:"Activo,Inactivo" }}</p>
                                <p>Stock: {{ menu.stock }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="footer-menu">
                    {% if user.username == 'admin' %}
                        <a href="{% url 'modificar_producto' menu.id %}" class="button-menu">Editar</a>
                    {% else %}
                        <a href="{% url 'detalle_menu' menu.id %}" class="button-menu">Ver detalles</a>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}