blog/urls.py
from django.urls import include, path
from blog import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.render_articles, name='index'),
    path('menus', views.menus, name = 'menus'),
    path('registro', views.registro , name = 'registro'),
    path('nosotros', views.nosotros, name = 'nosotros'),
    path('contacto', views.contacto, name = 'contacto'),
    path('login', views.login, name = 'login'),
    path('registro', views.registro, name = 'registro'),
    path('crud', views.crud, name = 'crud'),
    path('pago', views.pago, name = 'pago'),   
    path('agregar/<int:menu_id>/', views.agregar_menu, name='Add'),
    path('eliminar/<int:menu_id>/', views.eliminar_menu, name='Del'),
    path('restar/<int:menu_id>/', views.restar_menu, name='Sub'),
    path('limpiar/', views.limpiar_carrito, name='CLS'),
    path('agregar-producto/', views.agregar_producto, name='agregar_producto'),
    path('perfil/', views.perfil, name='perfil'),
    path('modificar-producto/<id>/', views.modificar_producto, name='modificar_producto'),
    path('editar_contacto/<int:id>/', views.editar_contacto, name='editar_contacto'),
    path('guardar_pedido/', views.guardar_pedido, name='guardar_pedido'),
    path('revisar_pedidos/', views.revisar_pedidos, name='revisar_pedidos'),
    path('menu/<int:menu_id>/', views.detalle_menu, name='detalle_menu'),
    path('agregar-proteina/', views.agregar_proteina, name='agregar_proteina'),
    path('agregar-salsa/', views.agregar_salsa, name='agregar_salsa'),
    path('agregar-vegetal/', views.agregar_vegetal, name='agregar_vegetal'),
    path('ingredientes/', views.lista_ingredientes, name='lista_ingredientes'),
    path('proteina/editar/<int:id>/', views.editar_proteina, name='editar_proteina'),
    path('proteina/eliminar/<int:id>/', views.eliminar_proteina, name='eliminar_proteina'),
    path('vegetal/editar/<int:id>/', views.editar_vegetal, name='editar_vegetal'),
    path('vegetal/eliminar/<int:id>/', views.eliminar_vegetal, name='eliminar_vegetal'),
    path('salsa/editar/<int:id>/', views.editar_salsa, name='editar_salsa'),
    path('salsa/eliminar/<int:id>/', views.eliminar_salsa, name='eliminar_salsa'),
    path('editar-usuario/', views.editar_usuario, name='editar_usuario'),
  
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    

]

    

santfood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('api/contactos/', include('contactos.urls')),
    path('api/menus/', include('menus.urls')),
    path('api/pedidos/', include('pedidos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

contactos/models.py
from django.db import models
from django.core.validators import MinValueValidator, RegexValidator, MinLengthValidator, EmailValidator
from django.db import models
from django.core.validators import (
    MinLengthValidator,
    RegexValidator,
    EmailValidator,
    ValidationError,
)
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError as DjangoValidationError

# Create your models here.


class Tipo_contacto(models.Model):
    tipo_contacto = models.CharField(
        max_length=20,
        validators=[
            MinLengthValidator(3),
            RegexValidator(
                regex='^[a-zA-ZñÑ]+$',
                message='El tipo de contacto solo puede contener letras y debe ser mayor a 3 letras'
            ),
        ]
    )

    def __str__(self):
        return self.tipo_contacto
    
class Estado_contacto(models.Model):
    estado_contacto = models.CharField(max_length=50)

    def __str__(self):
        return self.estado_contacto



def validate_unique_chars(value):
    previous_char = ''
    for char in value:
        if char == previous_char:
            raise ValidationError(
                _('El campo no puede contener caracteres repetidos consecutivos.'),
                code='invalid'
            )
        previous_char = char
        
def validate_message_sense(value):
    if len(set(value.lower())) < 10:
        raise ValidationError(
            _('El mensaje debe contener al menos 10 caracteres diferentes.'),
            code='invalid'
        )

class Contacto(models.Model):
    nombre = models.CharField(
        max_length=100,
        validators=[
            MinLengthValidator(3, message='El nombre debe tener al menos 3 caracteres'),
            RegexValidator(
                regex=r'^[a-zA-ZñÑ]+$',
                message='El nombre solo puede contener letras',
                code='invalid_nombre'
            ),
            validate_unique_chars
        ]
    )
    correo = models.EmailField(
    validators=[
        EmailValidator(message='Introduzca una dirección de correo electrónico válida'),
        RegexValidator(
            regex=r'^[^@]+@[a-zA-Z0-9.]{5,}\.[a-zA-Z]{2,4}$',
            message='El correo debe tener al menos 5 caracteres después del "@" y terminar en ".cl" o ".com"',
            code='invalid_correo'
            )
        ]
    )
    tipo_contacto = models.ForeignKey(Tipo_contacto, on_delete=models.PROTECT)
    mensaje_contacto = models.CharField(
        max_length=300,
        validators=[
            MinLengthValidator(10, message='El mensaje debe tener al menos 10 caracteres'),
            RegexValidator(
                regex=r'^(?!.*([^a-zA-Z. ñÑáéíóúÁÉÍÓÚ])).*$',
                message='El mensaje solo puede contener letras y puntos. Además, no pueden ser solo puntos.',
                code='invalid_mensaje_contacto'
            ),
            validate_unique_chars,
            validate_message_sense
        ]
    )
    estado_contacto = models.ForeignKey(Estado_contacto, on_delete=models.SET_DEFAULT, default=1, blank=True, null=True)
    respuesta = models.TextField(blank=True, null=True)
    
    def save(self, *args, **kwargs):
        if not self.nombre.strip():
            raise DjangoValidationError(_('El nombre no puede estar vacío o contener solo espacios en blanco.'))
        if not self.correo.strip():
            raise DjangoValidationError(_('El correo no puede estar vacío o contener solo espacios en blanco.'))
        if not self.mensaje_contacto.strip():
            raise DjangoValidationError(_('El mensaje no puede estar vacío o contener solo espacios en blanco.'))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nombre

menus/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, RegexValidator, MinLengthValidator


# Create your models here.

def no_tres_caracteres_repetidos(value):
    if len(value) >= 3:
        if value[0] == value[1] == value[2]:
            raise ValidationError(
                'El nombre no puede consistir en tres caracteres repetidos.',
                code='invalid'
            )

class Categoria(models.Model):
    nombre = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(3),
            no_tres_caracteres_repetidos,
            RegexValidator(
                regex='^[a-zA-ZñÑ ]+$',
                message='El nombre de la categoria solo puede contener letras y debe ser mayor a 3 letras'
            ),
        ],
        unique=True,
    )

    def __str__(self):
        return self.nombre

class Proteina(models.Model):
    nombre = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(3),
            no_tres_caracteres_repetidos,
            RegexValidator(
                regex='^[a-zA-ZñÑ ]+$',
                message='El nombre de la proteina solo puede contener letras y debe ser mayor a 3 letras'
            ),
        ],
        unique= True,
    )

    def __str__(self):
        return self.nombre
    
class Vegetal(models.Model):
    nombre = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(3),
            no_tres_caracteres_repetidos,
            RegexValidator(
                regex='^[a-zA-ZñÑ ]+$',
                message='El nombre del vegetal solo puede contener letras y debe ser mayor a 3 letras'
            ),
        ],
        unique=True,
    )

    def __str__(self):
        return self.nombre
    
class Salsa(models.Model):
    nombre = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(3),
            no_tres_caracteres_repetidos,
            RegexValidator(
                regex='^[a-zA-ZñÑ ]+$',
                message='El nombre de la salsa solo puede contener letras y debe ser mayor a 3 letras'
            ),
        ],
        unique=True,
    )

    def __str__(self):
        return self.nombre


class Menu(models.Model):
    nombre_menu = models.CharField(
        max_length=50,
        validators=[
            MinLengthValidator(8),
            no_tres_caracteres_repetidos,
            RegexValidator(
                regex='^[A-ZÑ][a-zA-ZñÑ ]+$',
                message='El nombre del menú debe comenzar con una letra mayúscula y solo puede contener letras y espacios.',
                code='invalid_nombre_menu'
            )
        ]
    )
    precio = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    ganancia = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    estado_menu = models.BooleanField()
    descripcion_menu = models.CharField(
        max_length=300,
        validators=[
            MinLengthValidator(10),
            RegexValidator(
                regex=r'^(?!^[.\s]*$)[a-zA-Z0-9áéíóúñÑÁÉÍÓÚ.,\s]+$',
                message='La descripción solo puede contener letras, números, puntos y espacios. No puede estar compuesta solo por puntos o espacios.',
                code='invalid_descripcion_menu'
            )
        ]
    )
    imagen = models.ImageField(upload_to='images/')
    proteina = models.ManyToManyField(Proteina)
    vegetal = models.ManyToManyField(Vegetal)
    salsa = models.ManyToManyField(Salsa)
    categoria = models.ManyToManyField(Categoria)
    stock = models.PositiveIntegerField()

    def __str__(self):
        return self.nombre_menu

    def clean(self):
        super().clean()

        if not self.descripcion_menu or len(self.descripcion_menu) < 10:
            raise ValidationError({
                'descripcion_menu': 'La descripción debe tener al menos 10 caracteres.'
            })


    

    

blog/forms.py
import re
from django import forms
from django.contrib.auth.forms import UserCreationForm
from menus.models import Menu, Proteina, Salsa, Vegetal
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        user_id = self.instance.id if self.instance else None 
        
        if User.objects.exclude(id=user_id).filter(email=email).exists():
            raise forms.ValidationError('Este email ya está en uso. Por favor, elige otro.')
        
        return email
    
    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if not re.match(r'^[A-Za-zñÑ]{1,15}$', first_name):
            raise forms.ValidationError('El nombre debe contener solo letras, máximo 15 caracteres y sin espacios.')

        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')

        if not re.match(r'^[A-Za-zñÑ ]{1,30}$', last_name):
            raise forms.ValidationError('Los apellidos debe contener solo letras y espacios, máximo 30 caracteres.')

        return last_name
    
    def clean_username(self):
        username = self.cleaned_data.get('username')

        if not re.match(r'^[A-Za-zñÑ]{1,15}$', username):
            raise forms.ValidationError('El username debe contener solo letras, máximo 15 caracteres y sin espacios.')

        return username


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(label='Email', max_length=254,
        validators=[
            RegexValidator(
                regex=r'^[^@]+@[a-zA-Z0-9.]{5,}\.[a-zA-Z]{2,4}$',
                message='El correo debe tener al menos 5 caracteres después del "@" y terminar en ".cl" o ".com"',
                code='invalid_email'
            )
        ]
    )

    username = forms.CharField(label='Username',
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z0-9]+$',
                message='El nombre de usuario solo puede contener letras y números',
                code='invalid_username'
            )
        ]
    )

    def clean_username(self):
        username = self.cleaned_data['username']
        
        # Validar caracteres repetidos consecutivos
        previous_char = ''
        for char in username:
            if char == previous_char:
                raise ValidationError('El nombre de usuario no puede contener caracteres repetidos consecutivos.')
            previous_char = char
        
        return username

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')




class MenuForm(forms.ModelForm):
    class Meta:
        model = Menu
        fields = '__all__'
        widgets = {
            'proteina': forms.CheckboxSelectMultiple,
            'vegetal': forms.CheckboxSelectMultiple,
            'salsa': forms.CheckboxSelectMultiple,
            'categoria': forms.CheckboxSelectMultiple,
        }

class ProteinaForm(forms.ModelForm):
    class Meta:
        model = Proteina
        fields = ['nombre']

class SalsaForm(forms.ModelForm):
    class Meta:
        model = Salsa
        fields = ['nombre']

class VegetalForm(forms.ModelForm):
    class Meta:
        model = Vegetal
        fields = ['nombre']
        

contactos/forms.py
from django import forms
from .models import Contacto


class ContactoForm(forms.ModelForm):
    
    class Meta:
        model = Contacto
        fields = ["nombre", "correo", "tipo_contacto", "mensaje_contacto"]
        
        


class ContactoAdminForm(forms.ModelForm):
    respuesta = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Contacto
        fields = ["estado_contacto", "respuesta"]

    def __init__(self, *args, **kwargs):
        super(ContactoAdminForm, self).__init__(*args, **kwargs)
        
        for field_name, field in self.fields.items():
            if field_name not in ["estado_contacto", "respuesta"]:
                field.widget.attrs['readonly'] = True

blog/templates/administracion/agregar.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
{% load crispy_forms_tags %}
{% if user.username == 'admin' %}

<br><br>
<div class = "container-agregar">
  {% if messages %}
    <div class="alert-container">
        {% for message in messages %}
            <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
    {% endif %}
  <form action="" class="formulario_agregar" method="post" enctype="multipart/form-data">

    <h2>Nuevo Producto</h2>

    <div class = "agregar">

      {% csrf_token %}
      {{ form.nombre_menu|as_crispy_field }}
      {{ form.precio|as_crispy_field }}
      {{ form.ganancia|as_crispy_field }}
      <br>
      {{ form.estado_menu|as_crispy_field }}
      <br>
      {{ form.descripcion_menu|as_crispy_field }}
      {{ form.imagen|as_crispy_field }}
      <br>
      {{ form.proteina|as_crispy_field}}
      <br>
      {{ form.vegetal|as_crispy_field }}
      <br>
      {{form.salsa|as_crispy_field }}
      <br>
      {{form.categoria|as_crispy_field }}
      <br>

    </div>
    <input type="submit" value = "Guardar">
    <input type="reset" value = "Cancelar">

  <form>
</div>
{% else %}
<div class="card">
    <h1>No tienes los permisos para ingresar a esta página</h1>
    <a href="{% url 'index' %}">Volver al inicio</a>
</div>
{% endif %}


<br><br>
{% endblock %}

blog/templates/administracion/agregar_proteina.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
{% load crispy_forms_tags %}
{% if user.username == 'admin' %}

<br><br>
<div class="container-agregar">
    {% if messages %}
    <div class="alert-container">
        {% for message in messages %}
            <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
    {% endif %}
  
  <form action="" class="formulario_agregar" method="post" enctype="multipart/form-data">
    <h2>Agregar una Proteina</h2>

    <div class="agregar">
        {% csrf_token %}
        {{ form.as_p }}
    </div>
    <input type="submit" value="Guardar">
    <input type="reset" value="Limpiar">
  </form>
</div>
{% else %}
<div class="card">
    <h1>No tienes los permisos para ingresar a esta página</h1>
    <a href="{% url 'index' %}">Volver al inicio</a>
</div>
{% endif %}
<br><br>
{% endblock %}

blog/templates/administracion/agregar_salsa.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
{% load crispy_forms_tags %}
{% if user.username == 'admin' %}

<br><br>
<div class="container-agregar">
    {% if messages %}
    <div class="alert-container">
        {% for message in messages %}
            <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
    {% endif %}
  
  <form action="" class="formulario_agregar" method="post" enctype="multipart/form-data">
    <h2>Agregar una Salsa</h2>

    <div class="agregar">
        {% csrf_token %}
        {{ form.as_p }}
    </div>
    <input type="submit" value="Guardar">
    <input type="reset" value="Limpiar">
  </form>
</div>
{% else %}
<div class="card">
    <h1>No tienes los permisos para ingresar a esta página</h1>
    <a href="{% url 'index' %}">Volver al inicio</a>
</div>
{% endif %}
<br><br>
{% endblock %}

blog/templates/administracion/agregar_vegetal.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
{% load crispy_forms_tags %}
{% if user.username == 'admin' %}

<br><br>
<div class="container-agregar">
    {% if messages %}
    <div class="alert-container">
        {% for message in messages %}
            <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    </div>
    {% endif %}
  
  <form action="" class="formulario_agregar" method="post" enctype="multipart/form-data">
    <h2>Agregar un Vegetal</h2>

    <div class="agregar">
        {% csrf_token %}
        {{ form.as_p }}
    </div>
    <input type="submit" value="Guardar">
    <input type="reset" value="Limpiar">
  </form>
</div>
{% else %}
<div class="card">
    <h1>No tienes los permisos para ingresar a esta página</h1>
    <a href="{% url 'index' %}">Volver al inicio</a>
</div>
{% endif %}
<br><br>
{% endblock %}

blog/templates/administracion/editar_ingrediente.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
{% load crispy_forms_tags %}
{% if user.username == 'admin' %}

<br><br>
<div class="container-editar">
  <form action="" class="formulario-editar" method="post" enctype="multipart/form-data">

    <h2>Editar {{ tipo_ingrediente|capfirst }}</h2>

    <div class="editar">
        {% csrf_token %}
        {{ form|crispy }}
    </div>
    <br>
    <input type="submit" value="Guardar" class="btn btn-primary">
    <a href="{% url 'lista_ingredientes' %}" class="btn btn-secondary">Cancelar</a>
  </form>
</div>
{% else %}
<div class="card">
    <h1>No tienes los permisos para ingresar a esta página</h1>
    <a href="{% url 'index' %}">Volver al inicio</a>
</div>
{% endif %}

<br><br>
{% endblock %}

blog/templates/administracion/modificar_contacto.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}

<br>
<div class="container-modificar-contacto">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <form method="post" class="modificar-contacto">
        {% csrf_token %}
        {{ form.contacto_id }}
        
        <h2>Editar Contacto</h2>
        
        <div class="form-group">
            <label for="id_nombre">Nombre</label>
            <p>{{ contacto.nombre }}</p>
        </div>
        
        <div class="form-group">
            <label for="id_correo">Correo</label>
            <p>{{ contacto.correo }}</p>
        </div>
        
        <div class="form-group">
            <label for="id_tipo_contacto">Tipo de Contacto</label>
            <p>{{ contacto.tipo_contacto }}</p>
        </div>
        
        <div class="form-group">
            <label for="id_mensaje_contacto">Mensaje</label>
            <p>{{ contacto.mensaje_contacto }}</p>
        </div>
        
        <div class="form-group">
            {{ form.estado_contacto.label_tag }}
            {{ form.estado_contacto }}
        </div>
        
        <div class="form-group">
            <label for="id_respuesta">Respuesta</label>
            {{ form.respuesta }}
        </div>

        <div class="form-footer">
            <input type="submit" value="Guardar">
        </div>
    </form>
</div>

<br>
{% endblock %}

blog/templates/administracion/modificar_menu.html
{% extends "base.html" %}
{% load static %}
{% block contenido %}
{% load crispy_forms_tags %}
{% if user.username == 'admin' %}



<br><br>
<div class = "container-editar">
  <form action="" class="formulario-editar" method="post" enctype="multipart/form-data">

    <h2>Editar Menu</h2>

    <div class = "editar">

        {% csrf_token %}
        {{ form | crispy }}

    </div>
    <br>
    <input type="submit" value = "Guardar">
    <input type="reset" value = "Cancelar">

  <form>
</div>
{% else %}
<div class="card">
    <h1>No tienes los permisos para ingresar a esta página</h1>
    <a href="{% url 'index' %}">Volver al inicio</a>
</div>
{% endif %}


<br><br>
{% endblock %}